# Generated by Django 5.0.4 on 2024-05-30 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_type_element_elementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlisting',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
